name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia às 00h UTC
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Renato-Ribeiroo
          outputs: dist/snake.svg

      - name: Deploy no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
