name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Renato-Ribeiroo
          outputs: dist/snake.svg?color_snake=%23ff00ff&color_dots=%23131313,%232a9d8f,%23264e70,%2300d4ff,%2300ffaa

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
